### ISSUE TITLE
Failed to upload apk, error:  APK specifies a version code that has already been used.

### ISSUE THREAD

**Issue by laumair** [bitrise-steplib/steps-google-play-deploy#31]
Hi.

Thank you for this tool. I am having some difficulty while deploying the apk to playstore. Currently we manually update the version code and version name before triggering the build. Despite of the version update I always get
`Failed to upload apk, error: googleapi: Error 403: APK specifies a version code that has already been used., apkUpgradeVersionConflict`

**Configuration**

```
 google-play-deploy@1.4.1:
        inputs:
        - mapping_file: android/app/build/outputs/mapping/release/mapping.txt
        - package_name: com.iota.packagename
        - apk_path: "$BITRISE_SIGNED_APK_PATH"
        - service_account_json_key_path: "$BITRISEIO_SERVICE_ACCOUNT_JSON_URL"
```
I'm really not sure how I can further debug but I do have the versions upgraded in the appropriate files.
 
I would greatly appreciate any help regarding this.
