### ISSUE TITLE
Build failed "Collection doesn't contain step (google-play-deploy) with version: 3.1.0"

### ISSUE THREAD

**Issue by omgaz** [bitrise-steplib/steps-google-play-deploy#88]
Hi guys, I received the following failed build error about an hour ago.

```
ERRO[03:09:41] Step (google-play-deploy@3.1.0) failed: stepman JSON steplib step info failed: query steplib step info: read step information: Collection doesn't contain step (google-play-deploy) with version: 3.1.0
```

bitrise.yml step / inputs

```
      - google-play-deploy@3.1.0:
          inputs:
            - package_name: xxxx
            - track: internal
            - service_account_json_key_path: xxxx
```

> Redacted sensitive information with `xxxx`
